### ISSUE TITLE
erreur empêchant le fonctionnement

### ISSUE THREAD

**Issue by PAVfr** [GenepixOnGithub/ip-geolocalizer#1]
Merci du partage,

En voulant regarder le fonctionnement, j'ai trouvé des erreurs:

A la ligne 64, il y a un `8` en trop:
https://github.com/GenepixOnGithub/ip-geolocalizer/blob/d65efdde7b0f47a0a6cafb60c97a3a2c78262b31/ipug.py#L64

L'emplacement du fichier json, n'est pas correct.
`apikey_jsonfile = "d:/python/ip-geolocalizer/apikey.json"`
Tous le monde ne l'a pas a cette emplacement.

**Comment by PAVfr** [comment]
Je viens de voir la maj, mais le lien n'a pas été modifié.

`?access_key={api_key}8&format=1`
devrait être 
`?access_key={api_key}&format=1`

sans le **8** sinon ça ne marche pas

**Comment by GenepixOnGithub** [comment]
Ah ! Oui pardon j'update ça :)
